### ISSUE TITLE
Please add the include class to the snippet list

### ISSUE THREAD

**Issue by dawnbarton** [SSAgov/genesys-vscode-extension#24]
Good morning,

Master page functionality described in the tutorial uses a snippet that does not appear to be listed in the main snippet list at https://github.com/SSAgov/genesys/blob/main/tutorials/08-Advanced-Topics/Using-Master-Page-Components.md

Please add gns-include-html when you have a chance. (Example from tutorial:  <div gns-include-html="navigation.html"></div> )

Thank you!

**Comment by CraigCecilSSA** [comment]
Good catch. I'll need to add the `gns-include` snippet and update the docs in that tutorial.

**Comment by CraigCecilSSA** [comment]
Resolved in https://github.com/SSAgov/genesys-vscode-extension/pull/26. Also, see https://github.com/SSAgov/genesys/blob/main/tutorials/08-Advanced-Topics/Using-Master-Page-Components.md for documentation updates regarding this.
