### ISSUE TITLE
Adding support for Patternfly design system

### ISSUE THREAD

**Issue by pankajshivpuje** [SSAgov/genesys-vscode-extension#37]
Need to add support for Patternfly design system so the open source community designers can gain ability to prototype in the browser.

PatternFly is an open source design system created to enable consistency and usability across a wide range of applications and use cases. PatternFly provides clear standards, guidance, and tools that help designers and developers work together more efficiently and build better user experiences.

[https://www.patternfly.org/v4/](url)

cc @CraigCecilSSA

**Comment by CraigCecilSSA** [comment]
Pankaj -- I can add a snippet the provides a basic starting page for Patternfly. However, if you are looking for a full-blown snippet library for all Patternfly components, then I suggest someone on your team create the JSON file for this, then create a PR with it attached, and I can generate a new Patternfly Snippets Extension for VS Code and place it in the VS Code Extensions Marketplace.

To help with this, look at the JSON file for the UEF Snippets extension: https://github.com/SSAgov/genesys-vscode-extension/blob/main/genesys-snippets.json

A great tool to help with creating these snippets is the Snippet Generator: https://snippet-generator.app/

Let me know if you have questions.

**Comment by pankajshivpuje** [comment]
@CraigCecilSSA Thank you. That sounds like a plan.

**Comment by CraigCecilSSA** [comment]
Added in #41

**Comment by CraigCecilSSA** [comment]
@pankajshivpuje Red Hat PatternFly 4 support has been added to the Genesys Extension for Visual Studio Code. You can now use the following two snippets to quickly create prototypes:

- `!!patternfly` (create a new PatternFly page)
- `gns-add-patternfly` (add PatternFly library to existing page)
